### ISSUE TITLE
Drupal CMS - Error Class Guzzle Psr7 Utils not found

### ISSUE THREAD

**Issue by NickStees** [http-interop/http-factory-guzzle#18]
I updated a Drupal 8.9.x CMS and now get an error when running cron 
`The website encountered an unexpected error. Please try again later.
Error. Class 'GuzzleHttp Psr7\Utils' not found in Http Factory Guzzle StreamFactory-->createStream() (line 21 of /mnt/www/html/acquiadev/vendor/http-interop/http-facto?y-guzzle/src/StreamFactory;.php).`

@nederdirk  and @shadowhand I think PR #13  introduced the problem. It appears I am using Guzzle 1.6.1 and there is no `GuzzleHttp\Psr7\Utils;` file in my /vendor GuzzleHttp Project.  https://github.com/guzzle/psr7/tree/1.6.1/src

Here are the current dependencies of the project 
![image](https://user-images.githubusercontent.com/2799150/126786023-edf684df-5866-491b-b08a-77cb713a035d.png)

I know this is likely will have to be solved in the Drupal Universe, but wanted to bring this up incase it breaks other projects. And maybe there are some other safeguards that can be put in place in your code?

**Comment by NickStees** [comment]
I was able to solve this by downgrading back to 1.0 and it was due to drupal module more info can be found here https://www.drupal.org/project/acquia_search/issues/3225101#comment-14172375

**Comment by shadowhand** [comment]
You are right, PR #13 is broken because the `function_exists` checks aren't using the full namespace, so it is not properly falling back to legacy Guzzle functions. 

I will make a patch release ASAP, and fix tests.

**Comment by shadowhand** [comment]
Fixed in version 1.1.1.
