### ISSUE TITLE
Failing test on Guzzle

### ISSUE THREAD

**Issue by Nyholm** [http-interop/http-factory-guzzle#2]
There is one test failing. Im not use it that is because the tests is wrong or the Guzzle PSR7 implementation is wrong. 

``` bash
1) Http\FactoryTest\ServerRequestFactoryTest::testCreateServerRequestFromGlobals
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-http://example.org/?foo=1&bar=true
+//example.org?foo=1&bar=true
```

Question, Is `//example.org?foo=1&bar=true` a valid URL?

Ping @shadowhand, @mindplay-dk (I see that you are not watching the 3 new repos)

**Comment by shadowhand** [comment]
Technically, yes it is a valid URL. But it should be including the scheme...

**Comment by mindplay-dk** [comment]
Strictly speaking, if it doesn't start with "*scheme*:", it's not a generic URL, but a [protocol-relative link](https://tools.ietf.org/html/rfc1738#section-2.3) - it doesn't make sense outside the context of another known URL, since there would be no way to identify the scheme and construct a URL from it.

**Comment by Nyholm** [comment]
Okey, good. I'll make a PR to Guzzle.

What about the missing slash? `.org?foo`. Is that okey?

**Comment by mindplay-dk** [comment]
Per [the Wikipedia entry](https://en.wikipedia.org/wiki/Uniform_Resource_Locator):

    scheme:[//[user:password@]host[:port]][/]path[?query][#fragment]

It appears that, yes, the slash is optional.

**Comment by Nyholm** [comment]
Good. That is what I believed as well. I'll update our tests


FYI: https://github.com/guzzle/psr7/pull/116
